use super::{Deserialize, Serialize};
#[derive(PartialEq, Eq, Serialize, Deserialize, Clone, Copy)]
pub enum GameState {
    Menu,
    Playing,
    Paused,
    GameOver,
    GameWon,
    Help,
    Settings,
    NftShop,
    SkillTree,
    Stats,
    Achievements,
    EnterName,
    ConfirmQuit,
    LevelEditor,
    LevelUp,
    Crafting,
    BountyBoard,
    MerchantShop,
    CompanionCamp,
    ClassSelect,
    Equipment,
    Casino,
    StockMarket,
    RealEstate,
}
