use super::{
    Boss, Goblin, HashSet, InGameUpgrade, Instant, Laser, Meteor, Point, PowerUp, Snake, Weather,
};
#[derive(Clone)]
pub struct HistoryState {
    pub snake: Snake,
    pub player2: Option<Snake>,
    pub food: Point,
    pub obstacles: HashSet<Point>,
    pub score: u32,
    pub bonus_food: Option<(Point, Instant)>,
    pub poison_food: Option<(Point, Instant)>,
    pub power_up: Option<PowerUp>,
    pub lives: u32,
    pub food_eaten_session: u32,
    pub campaign_level: u32,
    pub safe_zone_margin: u16,
    pub last_shrink_time: Instant,
    pub last_obstacle_spawn_time: Instant,
    pub combo: u32,
    pub last_food_time: Option<Instant>,
    pub lasers: Vec<Laser>,
    pub bosses: Vec<Boss>,
    pub portals: Option<(Point, Point)>,
    pub weather: Weather,
    pub lightning_column: Option<u16>,
    pub mines: HashSet<Point>,
    pub black_hole: Option<Point>,
    pub meteors: Vec<Meteor>,
    pub goblin: Option<Goblin>,
    pub xp: u32,
    pub player_level: u32,
    pub xp_to_next_level: u32,
    pub in_game_upgrades: std::collections::HashMap<InGameUpgrade, u32>,
    pub level_up_options: Vec<InGameUpgrade>,
    pub level_up_selection: usize,
}
