use super::{
    Boss, Companion, Goblin, HashSet, InGameUpgrade, Instant, Laser, Meteor, Point, PowerUp, Snake,
    Weather,
};
#[derive(Clone)]
pub struct HistoryState {
    pub snake: Snake,
    pub player2: Option<Snake>,
    pub bots: Vec<Snake>,
    pub bots_autopilot_paths: Vec<Vec<Point>>,
    pub food: Point,
    pub obstacles: HashSet<Point>,
    pub score: u32,
    pub bonus_food: Option<(Point, Instant)>,
    pub poison_food: Option<(Point, Instant)>,
    pub power_up: Option<PowerUp>,
    pub lives: u32,
    pub food_eaten_session: u32,
    pub campaign_level: u32,
    pub safe_zone_margin: u16,
    pub last_shrink_time: Instant,
    pub last_obstacle_spawn_time: Instant,
    pub combo: u32,
    pub last_food_time: Option<Instant>,
    pub lasers: Vec<Laser>,
    pub bosses: Vec<Boss>,
    pub portals: Option<(Point, Point)>,
    pub weather: Weather,
    pub lightning_column: Option<u16>,
    pub mines: HashSet<Point>,
    pub black_hole: Option<Point>,
    pub meteors: Vec<Meteor>,
    pub goblin: Option<Goblin>,
    pub xp: u32,
    pub player_level: u32,
    pub xp_to_next_level: u32,
    pub in_game_upgrades: std::collections::HashMap<InGameUpgrade, u32>,
    pub level_up_options: Vec<InGameUpgrade>,
    pub level_up_selection: usize,
    pub companion: Option<Companion>,
    pub equipment_boxes: Vec<Point>,
    pub fishing_timer: u32,
    pub fishing_progress: u32,
    pub is_fishing: bool,
    pub eggs_on_board: std::collections::HashMap<crate::snake::Point, crate::game::EggType>,
    pub mana: u32,
    pub max_mana: u32,
    pub time_of_day: crate::game::TimeOfDay,
    pub tick_counter: u32,
    pub p1_flag: Option<Point>,
    pub p2_flag: Option<Point>,
    pub p1_has_flag: bool,
    pub p2_has_flag: bool,
    pub p1_score: u32,
    pub p2_score: u32,
    pub xp_gems: HashSet<Point>,
}
