pub mod campaign_maps;
use crate::snake::{Direction, Point, Snake};
pub use campaign_maps::*;
use rand::{Rng, SeedableRng};
use serde::{Deserialize, Serialize};
use serde_with::serde_as;
use std::{
    collections::HashSet,
    fs::{self, File},
    io::{self, Read, Write},
};
use web_time::{Duration, Instant};

pub mod a_star_state;
pub mod achievement;
pub mod beep;
pub mod boss;
pub mod boss_type;
pub mod default_campaign_level;
pub mod default_elo;
pub mod default_lives;
pub mod default_skin;
pub mod default_unlocked_themes;
pub mod default_wrap_mode;
pub mod difficulty;
pub mod game_mode;
pub mod game_state;
pub mod game_struct;
pub mod goblin;
pub mod history_state;
pub mod in_game_upgrade;
pub mod laser;
pub mod meteor;
pub mod misc;
pub mod particle;
pub mod power_up;
pub mod planet;
pub mod power_up_type;
pub mod save_state;
pub mod shop_item;
pub mod statistics;
pub mod theme;
pub mod turret;
pub mod weather;

#[cfg(test)]
pub mod tests;

pub use a_star_state::*;
pub use achievement::*;
pub use beep::*;
pub use boss::*;
pub use boss_type::*;
pub use default_campaign_level::*;
pub use default_elo::*;
pub use default_lives::*;
pub use default_skin::*;
pub use default_unlocked_themes::*;
pub use default_wrap_mode::*;
pub use difficulty::*;
pub use game_mode::*;
pub use game_state::*;
pub use game_struct::*;
pub use goblin::*;
pub use history_state::*;
pub use in_game_upgrade::*;
pub use laser::*;
pub use meteor::*;
pub use misc::*;
pub use particle::*;
pub use power_up::*;
pub use planet::*;
pub use power_up_type::*;
pub use save_state::*;
pub use shop_item::*;
pub use statistics::*;
pub use theme::*;
pub use turret::*;
pub use weather::*;
pub mod bounty;
pub mod companion;
pub mod artifact;
pub mod craftable_item;
pub mod crop;
pub mod egg;
pub mod fish;
pub mod faction;
pub mod hero_class;
pub mod resource;
pub mod equipment;
pub mod stock;
pub use bounty::{Bounty, BountyType};
pub use companion::{Companion, CompanionType};
pub use artifact::Artifact;
pub use craftable_item::CraftableItem;
pub use crop::Crop;
pub use egg::EggType;
pub use fish::Fish;
pub use faction::Faction;
pub use hero_class::HeroClass;
pub use resource::Resource;
pub use equipment::Equipment;
pub mod real_estate;
pub mod vehicle;
pub use stock::Stock;
pub use real_estate::Property;
pub use vehicle::Vehicle;
